### PR TITLE
Google Site Verification / fb:admins / fb:app_id -> LocalSettings.php

### LINKED ISSUE #5: Move support for 'google-site-verification' to LocalSettings.php
As of version 1.1.1 it is possible to add the `google-site-verification` tag to any page though this is basically only useful on main page. However this is bad for the following reasons:
- Everybody able to edit main page may do so
- It allows for inserting arbitrary verification code making it possible to break an existing verification but also allows for foreign verification which is not intended.
  Thus a setting like `$egGoogleSiteVerifivation` which may hold the string seems like the solution to go.

### PR DESCRIPTION
**Pull request by octfx**
fixes #5 

I added support for JSON LD and the following config vars:

```
$wgGoogleSiteVerificationKey = null;
$wgFacebookAdmins = array();
$wgFacebookAppID = null;
$wgAddJSONLD = true;
```

### CODE REVIEW

**Comment by andru** [comment]
This looks great, thanks! I'll test it over the weekend and merge.

**Comment by andru** [comment]
Sorry for the delay in merging this. 

Do you know how to do an interactive rebase? It'd be good to squash all these commits down to just 1-3 commits covering key changes... it looks like some of these are bugfixes and small tweaks which can be squashed into their related functionality.

If you do, it'd be great if you could do that, force push to your branch again and this pull request should get updated; then i'll merge.

If not, I'll try to find time to handle that in the next couple weeks.

**Comment by FoXFTW** [comment]
Sorry, I accidently pushed to github.  
I cleaned up some code and wrote new commit messages

**Comment by gesinn-it** [comment]
... can this PR be merged please?

**Comment by andru** [comment]
Merged this manually to fix some conflicts and the pull request went straight up crazy but this is now in master, so I'm closing this :)

**Comment by andru** [comment]
(PS: Thanks @FoXFTW !)

**Pull request closed without merging**
